<a href="https://colab.research.google.com/github/Marshmellowon/DeepLearning_with_Pytorch/blob/master/Multi_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# XOR
- 단층 퍼셉트론으로는 구현이 불가능하다. 
- XOR문제는 multi layer 퍼셉트론으로 구현이 가능하다.
- input layer, hidden layer, output layer

# Back Propagation
- Back Propagation 그림
- 입력 이 있을때 output을 구하는데 
- loss에 대해 웨이트에 대한 미분값을 구함 loss값을 최소화 시킬수 있도록 웨이트를 없데이트 하는 것.
> backpropagation은 김성훈 교수꺼 보고 오기


In [28]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

# nn Layers
w1 = torch.Tensor(2,2).to(device)
b1 = torch.Tensor(2).to(device)
w2 = torch.Tensor(2,1).to(device)
b2 = torch.Tensor(1).to(device)

def sigmoid(x):
  # sigmoid func
  return 1.0 / (1.0 + torch.exp(-x))
  # return torch.div(torch.tensor(1), torch.add(torch.tensor(1.0), torch.exp(-x)))

def sigmoid_prime(x):
  # derivative of the sigmoid func
  return sigmoid(x) * (1 - sigmoid(x))


In [29]:
for step in range(10001):
  # forward
  l1 = torch.add(torch.matmul(X, w1), b1)
  print("l1 = \n", l1)

  a1 = sigmoid(l1)
  l2 = torch.add(torch.matmul(a1, w2), b2)
  Y_pred = sigmoid(l2)

  cost = -torch.mean(Y * torch.log(Y_pred) + (1 - Y) * torch.log(1 - Y_pred)) # binary cross entrophy

  # back prop
  # Loss derivative
  d_Y_pred = (Y_pred - Y) / (Y_pred * (1.0 - Y_pred) + 1e-7) # binary cross entrophy를 미분한것 1e-7은 0으로 나눠지는것을 방지

  # Layer 2
  d_l2 = d_Y_pred * sigmoid_prime(l2) 
  d_b2 = d_l2
  d_w2 = torch.matmul(torch.transpose(a1, 0, 1), d_b2) # transpose는 차원축을 지정할 수 있다. 두번째 인자값과 세번째 인자값을 바꿔서 한다.(5, 10) -> (10, 5)

  print('d_b2 = \n', d_b2)

  # Layer 1
  d_a1 = torch.matmul(d_b2, torch.transpose(w2, 0, 1)) # 왜 여기서 오류가 날까??? 일단 보류
  d_l1 = d_a1 * sigmoid_prime(l1)
  d_b1 = d_l1
  d_w1 = torch.matmul(torch.transpose(X, 0, 1), d_b1)

  # weight update
  w1 = w1 - learning_rate * d_w1 # gradient decent
  b2 = b1 - learning_rate * torch.mean(d_b1, 0)
  w2 = w2 - learning_rate * d_w2
  b2 = b2 - learning_rate * torch.mean(d_b2, 0)

  if step % 100 == 0:
    print(step, cost.item())


l1 = 
 tensor([[2.2995e-35, 0.0000e+00],
        [1.0000e+00, 0.0000e+00],
        [4.5989e-35, 0.0000e+00],
        [1.0000e+00, 0.0000e+00]])
d_b2 = 
 tensor([[ 0.5000],
        [-0.5000],
        [-0.5000],
        [ 0.5000]])
0 0.6931471824645996
l1 = 
 tensor([[2.2995e-35, 0.0000e+00],
        [1.0000e+00, 0.0000e+00],
        [4.6050e-35, 0.0000e+00],
        [1.0000e+00, 0.0000e+00]])
d_b2 = 
 tensor([[ 0.5000,  0.5000],
        [-0.5000, -0.5000],
        [-0.5000, -0.5000],
        [ 0.5000,  0.5000]])


RuntimeError: ignored